[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "RMCH"
version = "0.1.0"
description = "Rahil MSU CLM Hydro package for generating LHS parameter ensembles for CLM hydrology calibration"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
  {name = "Mohammad Uzair Rahil", email = "your_email_here@example.com"}
]
dependencies = [
  "numpy<2",
  "pandas<3",
  "xarray>=2023.1.0",
  "netCDF4>=1.6.0",
  "tqdm>=4.66"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
rahil = ["data/*.csv"]